### ISSUE TITLE
What is the traditional hand-eye calibration method compared in paper?

### ISSUE THREAD

**Issue by ZhuangTingT** [NVlabs/DREAM#15]
I have read paper of this Awesome work, and I wanna know the HEC method to learn more. Would you please give me a link or name of the HEC method? Thanks!

**Comment by TontonTremblay** [comment]
HEC? Sorry the first author cannot answer your questions, but I can try my best. hand-eye-calibration? https://github.com/lixiny/Handeye-Calibration-ROS it was something like this. I do not remember which one particularly.

**Comment by ZhuangTingT** [comment]
> HEC? Sorry the first author cannot answer your questions, but I can try my best. hand-eye-calibration? https://github.com/lixiny/Handeye-Calibration-ROS it was something like this. I do not remember which one particularly.

Thank you sincerely for your reply！
