### ISSUE TITLE
Is it simtrack necessary?

### ISSUE THREAD

**Issue by qdzr** [NVlabs/DREAM#16]
Hello,
Simtrack is used to refine your pose. However, simtrack seems not to be maintained. And unfortunately simtrack needs large gpu memory. I want to know if the error will be large without simtrack to refine the pose.  Or is there an alternative to simtrack?

**Comment by tabula-rosa** [comment]
Hello and thank you for your interest in DREAM!

Unfortunately I'm afraid I don't understand your question, since I don't think DREAM uses simtrack. Would you please provide more information or a reference to a file in the repository so that I can help with your inquiry? Thank you!

**Comment by qdzr** [comment]
I am sorry to express my issue unclearly. In README.md,  this paper, "Indirect Object-to-Robot Pose Estimation from an External Monocular RGB Camera"](https://research.nvidia.com/publication/2020-07_Indirect-Object-Pose) by Jonathan Tremblay, Stephen Tyree, Terry Mosier, and Stan Birchfield, is mentioned.
DREAM is used to present robot pose estimation framework and DOPE is used to find the pose of the object, which is then passed to another algorithm called SimTrack to refine the pose. What I want to know is if SimTrack plays an important role in this experiment. And  is there an alternative to simtrack to refine the pose of object?
Thanks for your reply very much.

**Comment by tabula-rosa** [comment]
Although I'm not an expert in that paper (and I would defer to @TontonTremblay if he has any suggestions here), I would say that SimTrack is not a strict requirement, only a useful capability for pose refinement. In principle, any pose refinement algorithm or software module should work. We have observed that sometimes there can be fluctuation of the pose output from DREAM, which depends on factors such as environmental lighting, so not all users would experience it. But this is where the pose refinement would be useful, especially if you wanted to also move the camera while DREAM is running.

For alternatives, one option could be modifying the multi-frame mode we offer in the DREAM ROS node. At present, the multi-frame mode works with a manual capture. But, one option is modifying this capability into an automatic queue. That is, every X seconds (X roughly between 0.1 to 2 seconds) the frame is automatically captured. Then, once Y frames (Y roughly between 5 and 20) are collected, you'd start dropping the oldest frame each time a new frame is captured. There is a buffer in the DREAM ROS node which is where the frames would be collected, and PnP is run on all of these frames. So, this option would turn the manual multi-frame mode into an automatic pose refinement capability that functions as a low-pass filter.

**Comment by qdzr** [comment]
Thanks for your reply. And your advice helps me a lot. I will close the issue now.
