### ISSUE TITLE
How can I get the label of panda robot like 000000.json?

### ISSUE THREAD

**Issue by qdzr** [NVlabs/DREAM#17]
Hello,
I want to make the label of panda robot dataset but I don't know how to realize it. Now I own a real panda robot and realsense D415.
![image](https://user-images.githubusercontent.com/92069587/176817362-7b03bac0-6415-4b5b-9f50-32635aacfc1b.png)
Can you provide some advice? Thank you!

**Comment by tabula-rosa** [comment]
Thank you for your continued interest in DREAM! There will be two types of files that are needed for the DREAM code to recognize the dataset as a valid NDDS dataset. The first are the data JSON files (as you mentioned), but the other is a camera intrinsics JSON file.

All 2d coordinates are with respect to the image space, in u/v ordering. +u is the coordinate along image width, and +v is the coordinate along image height. The units are pixels.
All 3d coordinates are with respect to the camera frame, in x/y/z ordering. The convention is +z is depth, so z is always positive if the keypoint is visible in the camera. +x is right, and +y is down. The units are meters.

For the data JSON file, here is a description of the field names:
- `objects`: list of robots (usually there is just one robot, but in principle, multiple could be supported)
- `objects:class`: name of the robot
- `objects:visibility`: _not currently used by DREAM_
- `objects:location`: the 3d coordinate of the robot's base frame (note that in our work, the keypoint `panda_link0` is defined at the base frame, so if you keep the same convention with the Panda, it would be the same)
- `objects:keypoints`: list of keypoints
- `objects:keypoints:name`: keypoint name
- `objects:keypoints:location`: 3d coordinate of the keypoint
- `objects:keypoints:projected_location`: 2d coordinate of the keypoint

Now, the second type of file is the camera intrinsics. This may be named `_camera_intrinsics.json` or similar. This is where you would store the intrinsics for the camera.
- `camera_settings': list of settings for each camera (however, DREAM assumes there is just one camera and will use the first in this list)
- `camera_settings:intrinsic_settings:fx` and `:fy`: the x- and y- focal length of the camera
- `camera_settings:intrinsic_settings:cx` and `:cy`: the u- and v- optical center of the camera
- `camera_settings:captured_image_size:width` and `:height`: the image resolution

I hope this clarifies the matter, and please let us know if there are any additional questions!

**Comment by tabula-rosa** [comment]
I'll go ahead and close this issue for now, but please re-comment if you run into problems and we can re-open this issue! Thanks!
