### ISSUE TITLE
Would you like to share the 3D model of panda robot？

### ISSUE THREAD

**Issue by lanlandefan** [NVlabs/DREAM#23]
Hello, this is a really wonderful article, and it can be widely used in the robot field.
Would you like to share the 3D model of panda robot？UE4 model or STL model or other formats. We want to further study and apply your methods by using 3D models，and I think it will contribute to the wide application and development of your method.
Thank you!

**Comment by TontonTremblay** [comment]
Let me check in nvidia if I can find the asset, the model we used was cleaned up by internal 3D artists.

**Comment by lanlandefan** [comment]
> Let me check in nvidia if I can find the asset, the model we used was cleaned up by internal 3D artists.

Thank you!

**Comment by TontonTremblay** [comment]
I found the kuka: https://www.dropbox.com/s/di3nq1af0i3w3x4/KUKArework.zip?dl=0 

Let me search for the pandas.

**Comment by TontonTremblay** [comment]
https://www.dropbox.com/s/yptnhww8nh3kdou/pandas_fbx.zip?dl=0 here is the pandas.

**Comment by lanlandefan** [comment]
> https://www.dropbox.com/s/yptnhww8nh3kdou/pandas_fbx.zip?dl=0 here is the pandas.

Sincerely thank you for your reply！
