### ISSUE TITLE
Saving synthetic datasets to synthetic/ directory

### ISSUE THREAD

**Issue by tabula-rosa** [NVlabs/DREAM#3]
Based on the README training example command (which assumes the data are located in `synthetic/`: `python scripts/train_network.py -i data/synthetic/panda_synth_train_dr/ ...`), I believe these two lines should be uncommented:

https://github.com/NVlabs/DREAM/blob/e4027801b74f416004faacf4d9152e77884bf8c3/data/DOWNLOAD.sh#L26

That, or the README should be updated to remove the `synthetic/` directory. I prefer saving the synthetic data into its own folder, but let me know your thoughts and I'll create a PR either way.

**Comment by sbirchfield** [comment]
Correct, these two lines should be uncommented.
